{% set name = "pydantic-pint" %}
{% set version = "0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pydantic_pint-{{ version }}.tar.gz
  sha256: ff79983d0b04c63ca3cb2bbd0568e9c016314ef4f669c339cbafeb8f9aa4a911

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - pint >=0.20
    - pydantic >=2.0

test:
  imports:
    - pydantic_pint
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/tylerh111/pydantic-pint
  dev_url: https://github.com/tylerh111/pydantic-pint
  doc_url: https://pydantic-pint.readthedocs.io
  summary: Pydantic validation for Pint Quantities.
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - tylerh111
